version: '3'

services:
  meet-me-here-postgres:
    container_name: meet-me-here-postgres
    image: postgres:15.1
    restart: always
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      POSTGRES_HOST: ${POSTGRES_HOST}
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DATABASE}
    volumes:
      - meet-me-here-postgres-data:/var/lib/postgresql/data
    command: postgres -p ${POSTGRES_PORT}

  meet-me-here-api:
    container_name: meet-me-here-api
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./:/app/api
    depends_on:
      - meet-me-here-postgres
    command: bash -c "npx prisma migrate dev && npm run dev"

volumes:
  meet-me-here-postgres-data: